### PR TITLE
Create deployability.md

### PR DESCRIPTION
**Pull request by mikedropmedia**
New feature snippet for deployability per @JohnLangford with Azure Personalizer service link.

### CODE REVIEW

**Comment by JohnLangford** [comment]
This seems good, except that it's available in more ways.  @eisber what would you suggest?

**Comment by eisber** [comment]
@mikedropmedia it's also part of Microsoft Machine Learning for Apache Spark (MMLSpark). See https://github.com/Azure/mmlspark

**Comment by JohnLangford** [comment]
This looks good to me---go ahead and merge.

**Comment by JohnLangford** [comment]
Not that I know of.

**Pull request merged**
